/**
 * The difficulty cards' pictures, photographed in the game's own renderer.
 *
 * They were SVG skylines drawn from code, which next to a real-time city read
 * as clip art. These are frames of the actual city -- the same renderer, the
 * same buildings -- at the hour and weather each difficulty stands for, framed
 * at the card's own 3:1 so `cover` crops nothing that matters.
 *
 *   node tools/card-art.mjs            # writes src/ui/setup-shots.ts
 *
 * Deterministic: the city, the hour and the weather front are all pinned, so
 * running it twice gives the same pictures.
 */

import { chromium } from 'playwright';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const W = 1320, H = 440;
const SHOTS = {
  // A warm morning over the low-rise edge of town, the towers far off.
  relaxed: { HOUR: 0.35, FRONT: 0.02, PITCH: 0.30, DIST: 300, FOCUS: '-1100,1100', YAW: 0.8 },
  // Downtown at golden hour, lights coming on against the low sun.
  standard: { HOUR: 0.74, FRONT: 0.1, PITCH: 0.15, DIST: 700, FOCUS: '0,0', YAW: 0.62 },
  // The same towers at night, in the rain.
  hard: { HOUR: 0.92, FRONT: 1, PITCH: 0.11, DIST: 650, FOCUS: '0,0', YAW: 3.6 },
};

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'card-art-'));
const shot = new URL('./city-shot.mjs', import.meta.url).pathname;
for (const [id, env] of Object.entries(SHOTS)) {
  execFileSync('node', [shot, path.join(tmp, `${id}.png`)], {
    env: { ...process.env, W: String(W), H: String(H), ...Object.fromEntries(
      Object.entries(env).map(([k, v]) => [k, String(v)])) },
    stdio: ['ignore', 'inherit', 'inherit'],
  });
}

// WebP through the browser's own encoder: no image library to install.
const browser = await chromium.launch({
  executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'],
});
const page = await browser.newPage();
const out = {};
for (const id of Object.keys(SHOTS)) {
  const png = fs.readFileSync(path.join(tmp, `${id}.png`)).toString('base64');
  out[id] = await page.evaluate(async (src) => {
    const img = new Image();
    img.src = src;
    await img.decode();
    const c = document.createElement('canvas');
    c.width = img.width; c.height = img.height;
    c.getContext('2d').drawImage(img, 0, 0);
    return c.toDataURL('image/webp', 0.8);
  }, `data:image/png;base64,${png}`);
}
await browser.close();

const kb = (s) => `${Math.round(s.length * 0.75 / 1024)} KiB`;
const body = `/**
 * The difficulty cards' pictures: frames of the real city, one per mood.
 *
 * Generated by tools/card-art.mjs -- do not edit by hand. ${W}x${H} WebP,
 * inlined because the game ships as one file.
 */

import type { DifficultyId } from '../sim/difficulty';

export const CARD_SHOTS: Record<DifficultyId, string> = {
${Object.entries(out).map(([id, uri]) => `  ${id}: '${uri}',`).join('\n')}
};
`;
fs.writeFileSync(new URL('../src/ui/setup-shots.ts', import.meta.url), body);
console.log('wrote src/ui/setup-shots.ts', Object.entries(out).map(([k, v]) => `${k} ${kb(v)}`).join(', '));
fs.rmSync(tmp, { recursive: true, force: true });
